// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.4
// source: api/proto/agent/v1alpha1/agent_service.proto

package agentv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolVersions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TarVersion     string                 `protobuf:"bytes,1,opt,name=tar_version,json=tarVersion,proto3" json:"tar_version,omitempty"`
	ZstdVersion    string                 `protobuf:"bytes,2,opt,name=zstd_version,json=zstdVersion,proto3" json:"zstd_version,omitempty"`
	StunnelVersion string                 `protobuf:"bytes,3,opt,name=stunnel_version,json=stunnelVersion,proto3" json:"stunnel_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolVersions) Reset() {
	*x = ToolVersions{}
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolVersions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolVersions) ProtoMessage() {}

func (x *ToolVersions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolVersions.ProtoReflect.Descriptor instead.
func (*ToolVersions) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1alpha1_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *ToolVersions) GetTarVersion() string {
	if x != nil {
		return x.TarVersion
	}
	return ""
}

func (x *ToolVersions) GetZstdVersion() string {
	if x != nil {
		return x.ZstdVersion
	}
	return ""
}

func (x *ToolVersions) GetStunnelVersion() string {
	if x != nil {
		return x.StunnelVersion
	}
	return ""
}

type PVCInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PvcName       string                 `protobuf:"bytes,1,opt,name=pvc_name,json=pvcName,proto3" json:"pvc_name,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	StorageClass  string                 `protobuf:"bytes,3,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	NodeAffinity  string                 `protobuf:"bytes,4,opt,name=node_affinity,json=nodeAffinity,proto3" json:"node_affinity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PVCInfo) Reset() {
	*x = PVCInfo{}
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVCInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVCInfo) ProtoMessage() {}

func (x *PVCInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVCInfo.ProtoReflect.Descriptor instead.
func (*PVCInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1alpha1_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *PVCInfo) GetPvcName() string {
	if x != nil {
		return x.PvcName
	}
	return ""
}

func (x *PVCInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PVCInfo) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *PVCInfo) GetNodeAffinity() string {
	if x != nil {
		return x.NodeAffinity
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Tools         *ToolVersions          `protobuf:"bytes,3,opt,name=tools,proto3" json:"tools,omitempty"`
	Pvcs          []*PVCInfo             `protobuf:"bytes,4,rep,name=pvcs,proto3" json:"pvcs,omitempty"`
	JwtToken      string                 `protobuf:"bytes,5,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1alpha1_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterRequest) GetTools() *ToolVersions {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *RegisterRequest) GetPvcs() []*PVCInfo {
	if x != nil {
		return x.Pvcs
	}
	return nil
}

func (x *RegisterRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1alpha1_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Pvcs          []*PVCInfo             `protobuf:"bytes,2,rep,name=pvcs,proto3" json:"pvcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1alpha1_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetPvcs() []*PVCInfo {
	if x != nil {
		return x.Pvcs
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1alpha1_agent_service_proto_rawDescGZIP(), []int{5}
}

var File_api_proto_agent_v1alpha1_agent_service_proto protoreflect.FileDescriptor

const file_api_proto_agent_v1alpha1_agent_service_proto_rawDesc = "" +
	"\n" +
	",api/proto/agent/v1alpha1/agent_service.proto\x12\x17katapult.agent.v1alpha1\"{\n" +
	"\fToolVersions\x12\x1f\n" +
	"\vtar_version\x18\x01 \x01(\tR\n" +
	"tarVersion\x12!\n" +
	"\fzstd_version\x18\x02 \x01(\tR\vzstdVersion\x12'\n" +
	"\x0fstunnel_version\x18\x03 \x01(\tR\x0estunnelVersion\"\x8d\x01\n" +
	"\aPVCInfo\x12\x19\n" +
	"\bpvc_name\x18\x01 \x01(\tR\apvcName\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12#\n" +
	"\rstorage_class\x18\x03 \x01(\tR\fstorageClass\x12#\n" +
	"\rnode_affinity\x18\x04 \x01(\tR\fnodeAffinity\"\xdd\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12;\n" +
	"\x05tools\x18\x03 \x01(\v2%.katapult.agent.v1alpha1.ToolVersionsR\x05tools\x124\n" +
	"\x04pvcs\x18\x04 \x03(\v2 .katapult.agent.v1alpha1.PVCInfoR\x04pvcs\x12\x1b\n" +
	"\tjwt_token\x18\x05 \x01(\tR\bjwtToken\"-\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"c\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x124\n" +
	"\x04pvcs\x18\x02 \x03(\v2 .katapult.agent.v1alpha1.PVCInfoR\x04pvcs\"\x13\n" +
	"\x11HeartbeatResponse2\xd3\x01\n" +
	"\fAgentService\x12_\n" +
	"\bRegister\x12(.katapult.agent.v1alpha1.RegisterRequest\x1a).katapult.agent.v1alpha1.RegisterResponse\x12b\n" +
	"\tHeartbeat\x12).katapult.agent.v1alpha1.HeartbeatRequest\x1a*.katapult.agent.v1alpha1.HeartbeatResponseBEZCgithub.com/maxitosh/katapult/api/proto/agent/v1alpha1;agentv1alpha1b\x06proto3"

var (
	file_api_proto_agent_v1alpha1_agent_service_proto_rawDescOnce sync.Once
	file_api_proto_agent_v1alpha1_agent_service_proto_rawDescData []byte
)

func file_api_proto_agent_v1alpha1_agent_service_proto_rawDescGZIP() []byte {
	file_api_proto_agent_v1alpha1_agent_service_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_v1alpha1_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_v1alpha1_agent_service_proto_rawDesc), len(file_api_proto_agent_v1alpha1_agent_service_proto_rawDesc)))
	})
	return file_api_proto_agent_v1alpha1_agent_service_proto_rawDescData
}

var file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_agent_v1alpha1_agent_service_proto_goTypes = []any{
	(*ToolVersions)(nil),      // 0: katapult.agent.v1alpha1.ToolVersions
	(*PVCInfo)(nil),           // 1: katapult.agent.v1alpha1.PVCInfo
	(*RegisterRequest)(nil),   // 2: katapult.agent.v1alpha1.RegisterRequest
	(*RegisterResponse)(nil),  // 3: katapult.agent.v1alpha1.RegisterResponse
	(*HeartbeatRequest)(nil),  // 4: katapult.agent.v1alpha1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 5: katapult.agent.v1alpha1.HeartbeatResponse
}
var file_api_proto_agent_v1alpha1_agent_service_proto_depIdxs = []int32{
	0, // 0: katapult.agent.v1alpha1.RegisterRequest.tools:type_name -> katapult.agent.v1alpha1.ToolVersions
	1, // 1: katapult.agent.v1alpha1.RegisterRequest.pvcs:type_name -> katapult.agent.v1alpha1.PVCInfo
	1, // 2: katapult.agent.v1alpha1.HeartbeatRequest.pvcs:type_name -> katapult.agent.v1alpha1.PVCInfo
	2, // 3: katapult.agent.v1alpha1.AgentService.Register:input_type -> katapult.agent.v1alpha1.RegisterRequest
	4, // 4: katapult.agent.v1alpha1.AgentService.Heartbeat:input_type -> katapult.agent.v1alpha1.HeartbeatRequest
	3, // 5: katapult.agent.v1alpha1.AgentService.Register:output_type -> katapult.agent.v1alpha1.RegisterResponse
	5, // 6: katapult.agent.v1alpha1.AgentService.Heartbeat:output_type -> katapult.agent.v1alpha1.HeartbeatResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_agent_v1alpha1_agent_service_proto_init() }
func file_api_proto_agent_v1alpha1_agent_service_proto_init() {
	if File_api_proto_agent_v1alpha1_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_v1alpha1_agent_service_proto_rawDesc), len(file_api_proto_agent_v1alpha1_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_v1alpha1_agent_service_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_v1alpha1_agent_service_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_v1alpha1_agent_service_proto_msgTypes,
	}.Build()
	File_api_proto_agent_v1alpha1_agent_service_proto = out.File
	file_api_proto_agent_v1alpha1_agent_service_proto_goTypes = nil
	file_api_proto_agent_v1alpha1_agent_service_proto_depIdxs = nil
}
