//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *VolumeTransfer) DeepCopyInto(out *VolumeTransfer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VolumeTransfer) DeepCopy() *VolumeTransfer {
	if in == nil {
		return nil
	}
	out := new(VolumeTransfer)
	in.DeepCopyInto(out)
	return out
}

func (in *VolumeTransfer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VolumeTransferList) DeepCopyInto(out *VolumeTransferList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolumeTransfer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VolumeTransferList) DeepCopy() *VolumeTransferList {
	if in == nil {
		return nil
	}
	out := new(VolumeTransferList)
	in.DeepCopyInto(out)
	return out
}

func (in *VolumeTransferList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VolumeTransferSpec) DeepCopyInto(out *VolumeTransferSpec) {
	*out = *in
}

func (in *VolumeTransferSpec) DeepCopy() *VolumeTransferSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeTransferSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VolumeTransferStatus) DeepCopyInto(out *VolumeTransferStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VolumeTransferStatus) DeepCopy() *VolumeTransferStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeTransferStatus)
	in.DeepCopyInto(out)
	return out
}
