apiVersion: apps/v1
kind: Deployment
metadata:
  name: katapult-web
  namespace: katapult-system
spec:
  template:
    spec:
      containers:
        - name: web
          image: katapult-web:local
          imagePullPolicy: Never
