apiVersion: v1
kind: ServiceAccount
metadata:
  name: katapult-controller
  namespace: katapult-system
  labels:
    app.kubernetes.io/name: katapult-controller
    app.kubernetes.io/component: controlplane
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: katapult-agent
  namespace: katapult-system
  labels:
    app.kubernetes.io/name: katapult-agent
    app.kubernetes.io/component: agent
